#!/usr/bin/env node
import { readFileSync, writeFileSync } from "node:fs";

const packageJson = JSON.parse(readFileSync("package.json", "utf8"));
const content = `// Generated by scripts/sync-version.mjs. Do not edit by hand.
export const CLI_VERSION = ${JSON.stringify(packageJson.version)};
`;

try {
    if (readFileSync("src/version.ts", "utf8") === content) {
        process.exit(0);
    }
}
catch {
    // File does not exist yet.
}

writeFileSync("src/version.ts", content);
